### ISSUE TITLE
Update BioHansel version

### ISSUE THREAD

**Issue by glabbe** [peterk87/nf-biohansel-sra-benchmark#1]
Hi @peterk87 , could you update the BioHansel version to 2.2.0 in the code?
 Line 87: 
  _conda 'bioconda::bio_hansel=2.1.1 conda-forge::pyahocorasick'_

**Comment by peterk87** [comment]
Hi @glabbe would you like to use this Nextflow workflow to benchmark biohansel with real world data? If so, I can make it a bit more cluster friendly and add a Snippy analysis step.

**Comment by glabbe** [comment]
Hi @peterk87 and thanks for the version update.  I was hoping we could run it both on the cluster (to test memory usage vs number of cores for 100 raw WGS datasets as you suggested), and also locally for runtime and memory usage for 25-100 raw datasets.  We just tried it on a local mac and it did record the runtime, but not memory usage:  "WARN: Task runtime metrics are not reported when using macOS without a container engine".  I think my colleague in Winnipeg has a Ubuntu OS (details in our manuscript), so I could also ask him to try it there instead.

**Comment by peterk87** [comment]
You *may* be able to get runtime metrics on MacOS if you run biohansel from within a Singularity container image, which would be no problem for me to make for this workflow.
 
Also, I could run the analysis on my Ubuntu 16.04 56-core machine :-)

So what you'd want is runtime stats from running biohansel against 100 read sets increasing number of threads? I could modify the script to run biohansel multiple times given a list of threads to use.

**Comment by glabbe** [comment]
It would be great if you could run it on your local machine.  I was thinking of plotting 1, 2, 4, 8, 16, and 32 threads for the 4 BioHansel schemes: what do you think?  I'll email the file with lists of 100 accessions for each scheme.
